import PageHeader from '../components/layout/PageHeader'

const SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    body: 'By accessing or using the Property & Billing Management System (PBMS), you agree to be bound by these Terms and Conditions. If you do not agree, please discontinue use immediately.',
  },
  {
    title: '2. Use of the Application',
    body: 'PBMS is provided for property management purposes only. You agree to use the application lawfully and not to misuse, reverse-engineer, or attempt to gain unauthorised access to any part of the system.',
  },
  {
    title: '3. User Accounts',
    body: 'You are responsible for maintaining the confidentiality of your login credentials. Any activity performed under your account is your responsibility. Notify your administrator immediately if you suspect unauthorised access.',
  },
  {
    title: '4. Data & Privacy',
    body: 'All tenant, billing, and property data entered into PBMS is stored locally on your device. The application does not transmit personal data to third-party servers without your explicit consent. You are responsible for the accuracy and legality of the data you enter.',
  },
  {
    title: '5. Billing & Invoices',
    body: 'Invoices and billing records generated by PBMS are for reference purposes. It is your responsibility to verify all figures before issuing invoices to tenants. PBMS is not liable for financial discrepancies arising from incorrect data entry.',
  },
  {
    title: '6. Sub-Users & Permissions',
    body: 'The account owner is responsible for all sub-users created under their organisation. Sub-user permissions must be assigned appropriately. The owner bears full responsibility for actions performed by sub-users.',
  },
  {
    title: '7. Intellectual Property',
    body: 'All content, design, and functionality within PBMS are the intellectual property of the developer. You may not copy, modify, or distribute any part of the application without prior written permission.',
  },
  {
    title: '8. Limitation of Liability',
    body: 'PBMS is provided "as is" without warranties of any kind. The developer shall not be liable for any direct, indirect, incidental, or consequential damages arising from your use of the application, including data loss or financial loss.',
  },
  {
    title: '9. Modifications',
    body: 'These Terms and Conditions may be updated from time to time. Continued use of the application after any changes constitutes your acceptance of the revised terms.',
  },
  {
    title: '10. Contact',
    body: 'For questions regarding these Terms and Conditions, please contact your system administrator or the application developer.',
  },
]

export default function TermsAndConditions() {
  return (
    <div className="app-shell">
      <PageHeader title="Terms & Conditions" />

      <div className="page-content scrollbar-hide p-4 space-y-3" style={{ paddingBottom: '32px' }}>

        {/* Intro banner */}
        <div className="bg-[#EAF0FF] rounded-xl px-4 py-3">
          <div className="text-[12px] font-bold text-[#1A3278] mb-0.5">Last updated: March 2026</div>
          <div className="text-[12px] text-[#1A3278]">
            Please read these terms carefully before using PBMS.
          </div>
        </div>

        {/* Sections */}
        {SECTIONS.map((s, i) => (
          <div key={i} className="bg-white rounded-xl border border-[#E3E5EA] px-4 py-3.5">
            <div className="text-[13px] font-bold text-[#1F1F1F] mb-1.5">{s.title}</div>
            <p className="text-[12px] text-[#707070] leading-relaxed">{s.body}</p>
          </div>
        ))}

      </div>
    </div>
  )
}
